version: '3'

services:
  delegation_server:
    build: ./docker/delegation_server
    network_mode: host
    image: delegation_server:latest
    restart: always
    privileged: true
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    ports:
      - 9998:9998
    entrypoint:
      - ./delegation_srvr
    logging:
      driver: json-file
      options:
        max-size: 10m

  ipfs_bc_if:
    build: ./docker/ipfs_bc_if
    image: ipfs_bc_if:latest
    restart: always
    ports:
      - 5007:5007
      - 12345:12345
    logging:
      driver: json-file
      options:
        max-size: 10m
