version: '3'
services:
  pave-vd-webui-nodejs:
    build:
      context: ./nodejs
      dockerfile: ./docker/pave/Dockerfile
    image: vd-bc-webui-nodejs
    network_mode: host
    volumes:
      - "./nodejs/config/pave:/home/node/app/config"
    container_name: pave-vd-webui-nodejs
    restart: always
    env_file:
      - "./nodejs/.env"

  pave-vd-webui-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: vd-pave-webui-nginx
    container_name: pave-vd-webui-nginx
    restart: always
    depends_on:
      - pave-vd-webui-nodejs
    ports:
      - "8881:80"
