version: '3'
services:
  vd-bc-webui-nodejs:
    build:
      context: ./nodejs
      dockerfile: ./docker/bc/Dockerfile
    image: vd-bc-webui-nodejs
    network_mode: host
    volumes:
      - "./nodejs/config/bc:/home/node/app/config/bc"
    container_name: vd-bc-webui-nodejs
    restart: always
    env_file:
      - "./nodejs/.env"

  vd-bc-webui-nginx:
    build:
      context: ./nginx
      dockerfile: ./bc/Dockerfile
    image: vd-bc-webui-nginx
    container_name: vd-bc-webui-nginx
    restart: always
    depends_on:
      - vd-bc-webui-nodejs
    ports:
      - "8881:80"
