version: '3'
services:
  vd-iota-webui-nodejs:
    build:
      context: ./nodejs
      dockerfile: ./docker/iota/Dockerfile
    image: vd-iota-webui-nodejs
    network_mode: host
    volumes:
      - "./nodejs/data:/home/node/app/data"
      - "./nodejs/config/iota:/home/node/app/config/iota"
    container_name: vd-iota-webui-nodejs
    restart: always
    env_file:
      - "./nodejs/.env"

  vd-iota-webui-nginx:
    build:
      context: ./nginx/iota
      dockerfile: Dockerfile
    image: vd-iota-webui-nginx
    container_name: vd-iota-webui-nginx
    restart: always
    depends_on:
      - vd-iota-webui-nodejs
    ports:
      - "6001:80"
