version: '3'
services:
  bc-ps-deployer:
    build:
      context: .
      dockerfile: ./docker/bc/deployer/Dockerfile
    image: "bc-ps-deployer:latest"
    container_name: "bc-ps-deployer"
    network_mode: "host"
    volumes:
      - "./config/bc:/home/node/app/config/"
    env_file:
      - ".env"
