version: '3'
services:
  ps-iota-rest:
    build:
      context: .
      dockerfile: ./docker/rest.dockerfile
    image: "ps-iota-rest"
    container_name: "ps-iota-rest"
    depends_on:
      - ps-iota-db
    restart: always
    ports:
      - "6008:6008"
    volumes:
      - "./config:/home/node/app/config"
    env_file:
      - ".env"
    links:
      - ps-iota-db:database
    networks:
      - ps-public
      - ps-local

  ps-iota-tcp:
    build:
      context: .
      dockerfile: ./docker/tcp.dockerfile
    image: "ps-iota-tcp"
    container_name: "ps-iota-tcp"
    depends_on:
      - ps-iota-db
    restart: always
    ports:
      - "6007:6007"
    volumes:
      - "./config:/home/node/app/config"
    env_file:
      - ".env"
    links:
      - ps-iota-db:database
    networks:
      - ps-public
      - ps-local

  ps-iota-db:
    build:
      context: .
      dockerfile: ./docker/db.dockerfile
    image: "ps-iota-db"
    container_name: "ps-iota-db"
    volumes:
      - "ps-iota-db-postgres:/var/lib/postgresql/data"
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    networks:
      - ps-local

volumes:
  ps-iota-db-postgres:

networks:
  ps-public:
  ps-local:
