#
# This file is part of the Frost distribution
# (https://github.com/iotaledger/frost)
# 
# Copyright (c) 2020 IOTA.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2.2'
services:
  ts-iota-rest:
    build:
      context: .
      dockerfile: ./docker/rest.dockerfile
    image: ts-iota-rest
    container_name: ts-iota-rest
    restart: always
    ports:
      - ${LISTENING_PORT}:${LISTENING_PORT}
    env_file:
      - .env

  ts-iota-hub-initializer:
    build:
      context: .
      dockerfile: ./docker/rest.dockerfile
    image: ts-iota-rest
    container_name: ts-iota-hub-initializer
    env_file:
      - .env
    entrypoint:
      - node
      - /home/node/app/dist/hub_init.js
