version: '3'
services:
  pave-vd-publisher:
    build:
      context: .
      dockerfile: ./docker/bc/Dockerfile
    image: bc-vd-publisher:latest
    container_name: pave-vd-publisher
    restart: always
    volumes:
      - "./config/pave:/home/node/app/config/"
      - "publisher-data:/home/node/app/data"
    network_mode: host
    env_file:
      - ".env"
    # depends_on:
    #   - pave-vd-ipfs

  # pave-vd-ipfs:
  #   image: ipfs/go-ipfs:latest
  #   container_name: pave-vd-ipfs
  #   volumes:
  #     - "ipfs_staging:/export"
  #     - "ipfs_data:/data/ipfs"
  #   ports:
  #     - "4001:4001"
  #     - "127.0.0.1:8080:8080"
  #     - "127.0.0.1:5001:5001"

volumes:
  publisher-data:
    driver: local
  # ipfs_staging:
  #   driver: local
  # ipfs_data:
  #   driver: local
