version: '3'
services:
  vd-iota-publisher:
    build:
      context: .
      dockerfile: ./docker/iota/Dockerfile
    image: vd-iota-publisher
    volumes:
      - "./data:/home/node/app/data"
      - "./config/iota:/home/node/app/config/iota"
    container_name: vd-iota-publisher
    restart: always
    network_mode: host
    # ports:
    #   - "6003:6003"
    env_file:
      - ".env"